# Generated by Django 4.0.6 on 2024-04-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.CharField(max_length=10)),
                ('decision', models.CharField(choices=[('DO_NOTHING', 'Do nothing'), ('BUY', 'Buy'), ('SELL', 'Sell')], max_length=20)),
                ('reason', models.CharField(choices=[('MARKET_CLOSED', 'Market closed'), ('SMA1_GT_SMA2', 'SMA1 > SMA2'), ('SMA2_GT_SMA1', 'SMA2 > SMA1'), ('NO_CROSSOVER', 'No crossover'), ('ALREADY_OPEN', 'Already have an open position')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=20)),
            ],
        ),
    ]
